# Generated by Django 5.1.1 on 2024-09-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='send',
            field=models.BooleanField(default=True),
        ),
    ]
