# Generated by Django 4.2.3 on 2024-09-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='agreement',
        ),
    ]
